# Note : The RemoteCamera jar needs to be called with the parameter currentCameraID={camera_number}
# e.g. cameraID=1 OR cameraId=2 (OR, 3, 4, 5 ..., depending on how many cameras have been deployed)

#***************************************
# The total number of cameras deployed in the project
cameras.total=4

# All cameras use the same port number. This is OK since each camera is running on a separate machine,
# which implies that they each have different host IP's.
# The tcp port that each of those camera processes use
tcp.port=54555

# The udp ports are different for each camera, even though the host IP's are different. This enables a key
# aspect, which is the discovery of host IP's dynamically. This dynamic discovery ensures that we do not have to track
# the host IP addresses in this file.

# Note: a) There must be as many udp ports mentioned as number of servers
#       b) If the udp ports are not unique, both the server and client programs will abort

# The udp port that the first camera uses
1.udp.port=54777

# The udp port that the second camera uses
2.udp.port=54778

# The udp port that the third camera uses
3.udp.port=54779

# The udp port that the fourth camera uses
4.udp.port=54780

#width, height
#1.Text\ Inspection.characterDimensions=11,14
#1.Text\ Inspection.characterDimensions=22,14
#AL1.Left\ IP.Text\ Inspection.characterDimensions=22,18
AL1.Left\ IP.Text\ Inspection.characterDimensions=19,21
AL1.Left\ IP.Text\ Inspection.thickness=Thick

#width, height
AL1.Right\ IP.Text\ Inspection.characterDimensions=20,24
AL1.Right\ IP.Text\ Inspection.thickness=Thin

#width, height
#1.Text\ Inspection.characterDimensions=11,14
#1.Text\ Inspection.characterDimensions=22,14
AL2.Left\ IP.Text\ Inspection.characterDimensions=22,18
AL2.Left\ IP.Text\ Inspection.thickness=Thick

#width, height
AL2.Right\ IP.Text\ Inspection.characterDimensions=20,24
AL2.Right\ IP.Text\ Inspection.thickness=Thin

# The timeout in milliseconds for clients to connect with the server
timeout.millis=5000

#************************************************
# Save the original images received in the client and server cameras
save.original.client=true
save.original.server=true

#**************************************************
tesseract.datapath=E:/TechWerx/CosTheta/IntelliJ IDEA Projects/RemoteCamera/External Libraries/tessdata

#**************************************************
#cameracommand=sudo raspistill -t 20 --nopreview -e png
use.capricam=true
cameracommand=sudo raspistill --width 2028 --height 1520 --nopreview -t 100 --quality 100 -e jpg -th none
idl=1
sdl=1
