#define the clipbox coordinates
#form is {PartName}.{Inspection Point Name}.{Processor Name}.clipBox=startX,startY,width,height e.g.
#AL1.Left\ IP.Text\ Inspection.clipBox=475,670,860,310
#Note: If the names have a space ' ' in the key name, ensure that the space is
#represented by a '\ '
# if a clipping region is not defined for a processor, the full image is used

AL1.Left\ IP.Text\ Inspection.clipBox=475,670,860,310
AL1.Right\ IP.Text\ Inspection.clipBox=100,620,690,290
AL2.Left\ IP.Text\ Inspection.clipBox=475,670,860,310
AL2.Right\ IP.Text\ Inspection.clipBox=100,620,690,290
